export const queryKeys = {
  apps: ['apps'] as const,
  app: (id: string) => ['apps', id] as const,
  categories: ['categories'] as const,
  system: ['system'] as const,
  systemNetwork: ['system', 'network'] as const,
  systemPostgres: ['system', 'postgres'] as const,
  terminalConfig: ['terminal', 'config'] as const,
  appHistory: (id: string, hours: number, limit: number) => ['apps', id, 'history', hours, limit] as const,
  dockerContainers: ['docker', 'containers'] as const,
  dockerContainer: (name: string) => ['docker', 'containers', name] as const,
  appDocker: (id: string) => ['apps', id, 'docker'] as const,
  machines: ['machines'] as const,
  machine: (id: string) => ['machines', id] as const,
  topology: ['machines', 'topology'] as const,
  discovered: ['machines', 'discovered'] as const,
  logs: ['logs'] as const,
  log: (id: number) => ['logs', id] as const,
  logApplications: ['logs', 'applications'] as const,
  files: ['files'] as const,
  filesConfig: ['files', 'config'] as const,
  fileList: (path: string) => ['files', path] as const,
}
